### ISSUE TITLE
[Enhancement] Update logging in all functions to utilize Sawmill

### ISSUE THREAD

**Issue by adilanchian** [PixelogicDev/gruveebackend#55]
We not have a logger! Yay333t!! Time to do some proper clean up with all the log statements in the backend 👍

**Comment by adilanchian** [comment]
@LeviHarrison down for this as well?

**Comment by LeviHarrison** [comment]
Following up on our conversation over Discord yesterday, I think that there might have to be a few changes to Sawmill in order to support Emoji in logs. We could technically append them on the error messages that we pass to `LogErr`, but that's a little bit messy, and it would also lead to them showing up in the GCP Logs Viewer, where they aren't really needed. That's why I propose that we add one more parameter to `LogErr` which either takes an emoji or a type representing that emoji, such as `sawmill.Network`, which could be 🌐 and represent a network error. Thoughts?

**Comment by adilanchian** [comment]
Hey sorry I know I'm behind on this. Will take a look at this after the stream!

**Comment by adilanchian** [comment]
Okay so:

- I feel like the logging in GCP would be valid for this as well no? Would definitely love to understand your reasoning behind this
- I did something similar to what you are proposing for iOS! Essentially have some set emojis that are always added to the front of the log based on whether it was info/warning/error etc. Could you do something similar to this where we allow people to pass in an optional emoji for different severity levels and such?

Yes definitely feel free to make changes to Sawmill as needed!

**Comment by adilanchian** [comment]
Alright so there was a stupid massive merge conflict between your branch and master so I was able to pull in your changes to fix them all. I did in turn pull your changes (it was easier). Hopefully everything should be good to go :D. I do need to rev the version for some pkgs for proper deployment to Firebase. But good to go!
